WebNhomKinh/Controllers/AdminQuanLyHangController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WebNhomKinh.Models;

namespace WebNhomKinh.Controllers
{
    public class AdminQuanLyHangController : Controller
    {
        // GET: AdminQuanLyHang
        [HttpGet]
        public ActionResult Index(string searchString, int? page)
        {
            if (Session["MaTKAdmin"]==null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                try
                {
                    var model = new QuanLyHangSX()
                    {
                        DanhSachHangSanXuat = KhoiTao(searchString, page)
                    };
                    return View(model);
                }
                catch (Exception)
                {

                    return View();
                }
               
            }
            
        }

        public IPagedList<HangSanXuat> KhoiTao(string searchString, int? page)
        {

            ViewBag.CurrentFilter = searchString;
            ShopEntities shop = new ShopEntities();

            var dsHang = shop.HangSanXuats.OrderByDescending(s => s.MaHang);
            if (!String.IsNullOrEmpty(searchString))
            {
                dsHang = shop.HangSanXuats.Where(s => s.TenHang.Contains(searchString)).OrderByDescending(s => s.MaHang);
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            dsHang.ToPagedList(pageNumber, pageSize);
            return dsHang.ToPagedList(pageNumber, pageSize);
        }

        public ActionResult ThemHangSX(QuanLyHangSX qlhang, HttpPostedFileBase file, string submit, int id, string img)
        {
            if (Session["MaTKAdmin"]==null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                try
                {
                    var model = new QuanLyHangSX()
                    {
                        DanhSachHangSanXuat = KhoiTao("", 1)
                    };
                    ShopEntities shop = new ShopEntities();
                    if (submit == "Thêm")
                    {
                        file = file ?? Request.Files["file"];
                        if (file != null && file.ContentLength > 0)
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            if (fileName != null)
                            {
                                var path = Path.Combine(Server.MapPath("~/Images/HangSXs/"), fileName);
                                file.SaveAs(path);
                            }
                            HangSanXuat hang = new HangSanXuat();

                            hang.TenHang = qlhang.HangSanXuat.TenHang;
                            hang.LinkWeb = qlhang.HangSanXuat.LinkWeb;
                            hang.AnhDaiDien = "/Images/HangSXs/" + fileName;
                            shop.HangSanXuats.Add(hang);
                            shop.SaveChanges();
                        }
                    }
                    if (submit == "Sửa")
                    {
                        var hang = shop.HangSanXuats.SingleOrDefault(h => h.MaHang == id);
                        file = file ?? Request.Files["file"];
                        if (file != null && file.ContentLength > 0)
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            if (fileName != null)
                            {
                                var path = Path.Combine(Server.MapPath("~/Images/HangSXs/"), fileName);
                                file.SaveAs(path);

                                hang.TenHang = qlhang.HangSanXuat.TenHang;
                                hang.LinkWeb = qlhang.HangSanXuat.LinkWeb;
                                hang.AnhDaiDien = "/Images/HangSXs/" + fileName;
                                shop.SaveChanges();
                            }
                        }
                        else
                        {
                            hang.TenHang = qlhang.HangSanXuat.TenHang;
                            hang.LinkWeb = qlhang.HangSanXuat.LinkWeb;
                            hang.AnhDaiDien = img;
                            shop.SaveChanges();
                        }
                    }


                    return RedirectToAction("Index", model);
                }
                catch (Exception)
                {

                    return RedirectToAction("Index");
                }
                
            }
           

        }
        [HttpPost]
        public ActionResult XoaHang(int id)
        {
            if (Session["MaTKAdmin"]==null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                try
                {
                   
                    ShopEntities shop = new ShopEntities();
                    var hang = shop.HangSanXuats.Single(s => s.MaHang == id);
                    var dsChiTietSP = shop.ChiTietSanPhams.Where(c => c.MaNhaSanXuat == id).ToList();
                    foreach (var item in dsChiTietSP)
                    {

                        var sp = shop.SanPhams.SingleOrDefault(s => s.MaSanPham == item.MaSanPham);
                        shop.ChiTietSanPhams.Remove(item);
                        shop.SanPhams.Remove(sp);
                        shop.SaveChanges();
                    }
                    shop.HangSanXuats.Remove(hang);
                    shop.SaveChanges();
                    return Json(JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {

                    return RedirectToAction("Index");
                }
               
            }
            
        }
    }
}

WebNhomKinh/Views/AdminQuanLyHang/Index.cshtml
@using WebNhomKinh.Models

@{
    ViewBag.Title = "Quản lý hãng sản xuất";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ShopEntities shop = new ShopEntities();
}
<link href="~/Content/validationEngine.jquery.css" rel="stylesheet" />
@using PagedList
@using PagedList.Mvc
@using WebNhomKinh.Models
@model QuanLyHangSX
<style>
    .btn-file {
        position: relative;
        overflow: hidden;
    }

        .btn-file input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            min-width: 100%;
            min-height: 100%;
            font-size: 100px;
            text-align: right;
            filter: alpha(opacity=0);
            opacity: 0;
            outline: none;
            background: white;
            cursor: inherit;
            display: block;
        }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">

                <li>
                    <i class="fa fa-dashboard">
                        <a>
                            @Html.ActionLink("Trang chủ", "Index", "Admin")
                        </a>

                    </i>
                </li>

                <li class="active">
                    <i class="fa fa-edit"></i> Quản lý hãng sản xuất
                </li>

            </ol>
        </div>


        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-lg">
                @using (Html.BeginForm("ThemHangSX", "AdminQuanLyHang", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmThem" }))
                {
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Hãng sản xuất</h4>

                        </div>
                        <div class="modal-body">


                            <div class="panel-body">
                                <input type="hidden" name="id" id="txtId" value="0">

                                <div class="form-group">
                                    <label>Tên Hãng</label>
                                    @Html.TextBoxFor(m => m.HangSanXuat.TenHang, new { id = "txttenhang", @class = "form-control validate[required]", placeholder = "Tên hãng" })

                                </div>

                                <div class="form-group">
                                    <label>Ảnh đại diện</label>
                                    <div class="input-group">

                                        <span class="input-group-btn">
                                            <span class="btn btn-default btn-file">

                                                Chọn ảnh&hellip; <input type="file" name="file" class="form-control" multiple>
                                            </span>
                                        </span>
                                        <input type="text" class="form-control" id="img" name="img" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Website</label>
                                    @Html.TextBoxFor(m => m.HangSanXuat.LinkWeb, new { id = "txtwebsite", @class = "form-control", placeholder = "Trang web" })

                                </div>
                            </div>
                        </div>

                        <div class="modal-footer">
                            <input type="submit" name="submit" id="bt_Them" class="btn btn-default" value="Thêm" />
                            <input type="submit" name="submit" id="bt_Sua" class="btn btn-default" value="Sửa" />
                            <input type="reset" class="btn btn-default" onclick="Huy()" value="Làm lại">
                        </div>

                    </div>
                }
            </div>
        </div>

    </div>
    <div class="box box-solid">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-lg-4">
                    <a class="btn btn-app" id="Dialog_them" data-toggle="modal" data-target="#myModal"><i class="fa fa-edit"></i>Thêm </a>
                    <a class="btn btn-app" id="bt_xoa_all" style="display: none"><i class="fa fa-remove"></i>Xóa </a>
                    <a class="btn btn-app" id="bt_huy_all" style="display: none"><i class="fa fa-remove"></i>Hủy </a>
                 </div>
                <div class="col-lg-8">
                    <form action="/AdminQuanLyHang/Index" id="fromTimKiem">
                        <div class="col-lg-4" style="margin-left: 170px; float: right">
                            <label></label>
                            <div>
                                <div class="form-group input-group">
                                    <input type="text" name="searchString" class="form-control" placeholder="Tìm Kiếm.........">
                                    <span class="input-group-btn"><button class="btn btn-default" type="button" onclick="$('#fromTimKiem').submit();"><i class="fa fa-search"></i></button></span>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-lg-12">

                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-striped" id="tb_hangsx">
                            <thead>
                                <tr><th><input type="checkbox" name="checkAll" id="checlAll" /></th>
                                    <th>Mã hãng</th>
                                    <th>Tên hãng</th>
                                    <th>Ảnh</th>
                                    <th>Trang web </th>
                                    <th>Sửa</th>
                                    <th>Xóa</th>
                                </tr>
                            </thead>
                            <tbody id="table-body">
                                @foreach (var item in Model.DanhSachHangSanXuat)
                                {
                                    <tr><td><input type="checkbox" name="check" id="check" /></td>
                                        <td>@item.MaHang</td>
                                        <td>@item.TenHang</td>
                                        <td><img id="img" src="@item.AnhDaiDien" style="width: 50px; height: 50px;" /></td>
                                        <td>@item.LinkWeb</td>
                                        <td>
                                            <button type="button" onclick="Sua(this)" class="btn btn-sm" data-toggle="modal" data-target="#myModal">Sửa</button>
                                        </td>
                                        <td>
                                            <button type="button" onclick="Xoa(this)" class="btn btn-sm">Xóa</button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        @Html.PagedListPager(Model.DanhSachHangSanXuat, page => Url.Action("Index", new { page }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.validationEngine.js"></script>
<script src="~/Scripts/jquery.validationEngine-en.js"></script>
<Script>

    $("#Dialog_them").click(function () {

        $("#bt_Sua").hide();
        $("#bt_Them").show();
    });

    $("#frmThem").validationEngine();

    $("#bt_Them").click(function () {
        if ($("#frmThem").valid()) {
            $("#frmThem").submit();
        };
    });
    $(document).on('change', '.btn-file :file', function () {
        var input = $(this),
            numFiles = input.get(0).files ? input.get(0).files.length : 1,
            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.trigger('fileselect', [numFiles, label]);
    });

    $(document).ready(function () {
        $('.btn-file :file').on('fileselect', function (event, numFiles, label) {

            var input = $(this).parents('.input-group').find(':text'),
                log = numFiles > 1 ? numFiles + ' files selected' : label;

            if (input.length) {
                input.val(log);
            } else {
                if (log) alert(log);
            }

        });
    });
    function Huy() {
        $("#bt_Sua").hide();
        $("#bt_Them").show();
    }
    $("#bt_Sua").hide();
    function Sua(el) {
        event.preventDefault();
        $("#bt_Sua").show();
        $("#bt_Them").hide();
        $("#txtId").val(el.parentNode.parentNode.cells[1].textContent);
        $("#txttenhang").val(el.parentNode.parentNode.cells[2].textContent);
        $("#file").val($(el.parentNode.parentNode.cells[3]).find('img').attr('src'));
        $("#img").val($(el.parentNode.parentNode.cells[3]).find('img').attr('src'));
        $("#txtwebsite").val(el.parentNode.parentNode.cells[4].textContent);

    }
    function Xoa(el) {
        var mid = el.parentNode.parentNode.cells[1].textContent;
        $.ajax({
            url: '/AdminQuanLyHang/XoaHang/' + mid + '',
                        type: 'POST',
                        dataType: 'json',
                        success: function () {
                            alert("Xóa thành công");
                            window.location.reload();
                        },
                        error: function () {
                            alert("Xóa thất bại");
                            window.location.reload();
                        }
                    });
    }
    var count = 0;
    $(window).load(function () {
        $('#checlAll').change(function () {
            $("input:checkbox").prop('checked', $(this).prop("checked"));
            if (this.checked) {
                $("#bt_xoa_all").show();
                $("#Dialog_them").hide();
                $("#bt_huy_all").show();
            }
            else {

                $("#bt_xoa_all").hide();
                $("#Dialog_them").show();
                $("#bt_huy_all").hide();
            }
        });

        $("input[type='checkbox']").change(function (e) {
            if ($(this).is(":checked")) {
                count++;

            } else {
                count--;

            }
            if (count > 0) {
                $("#bt_xoa_all").show();
                $("#bt_huy_all").show();
                $("#Dialog_them").hide();
            } else {
                $("#bt_xoa_all").hide();
                $("#bt_huy_all").hide();
                $("#Dialog_them").show();
            }
        });
        $("#bt_huy_all").click(function () {
            $("#bt_xoa_all").hide();
            $("#bt_huy_all").hide();
            $("#Dialog_them").show();
            $("input:checkbox").attr('checked', false);
        });
        $("#bt_xoa_all").click(function () {
            $("table#tb_hangsx > tbody > tr").each(function () {
                var ck = $(this).find("input[type='checkbox']");
                var id = $(this).find("td").eq(1).html();
                if (ck.is(":checked")) {
                    $.ajax({
                        url: '/AdminQuanLyHang/XoaHang/?id=' + id + '',
                        type: 'POST',
                        dataType: 'json',
                        success: function () {
                            return true;
                        },
                        error: function () {
                            return false;
                        }
                    });
                }

            });
            if (true) {
                alert("Xóa thành công");
                window.location.reload();
            } else {
                alert("Xóa thất bại");
                window.location.reload();
            }
        });
    });
</Script>