WebNhomKinh/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using WebNhomKinh.Models;
using System.Configuration;
using System.Net.Mail;

namespace WebNhomKinh.Controllers
{
    public class GioHangController : Controller
    {
        // GET: GioHang
     
        public ActionResult XoaSanPham(int id)
        {
            ShoppingCart objCart = (ShoppingCart)Session["Cart"];
            if (objCart != null)
            {
                objCart.RemoveFromCart(id);
                Session["Cart"] = objCart;
            }
            return RedirectToAction("index");
        }
        // thêm vào giỏ hàng 1 sản phẩm có id = id của sản phẩm
        [HttpPost]
        public ActionResult ThemVaoGioHang(int id,int soLuong)
        {
          
                ShopEntities db = new ShopEntities();
                var p = db.SanPhams.SingleOrDefault(s => s.MaSanPham.Equals(id));
                decimal?gia = 0;
                gia = p.GiaGiam > 0 ? p.GiaGiam : p.Gia;

                if (p != null)
                {
                    ShoppingCart objCart = (ShoppingCart)Session["Cart"];
                    if (objCart == null)
                    {
                        objCart = new ShoppingCart();
                    }
                    ShoppingCart.ShoppingCartItem item = new ShoppingCart.ShoppingCartItem()
                    {
                        Image = p.AnhDaiDien,
                        ProductName = p.TenSanPham,
                        ProductID = p.MaSanPham,
                      
                        Price = gia.ToString(),
                        Quanlity = soLuong,
                        Total = Convert.ToDouble(gia.ToString().Trim().Replace(",", string.Empty).Replace(".", string.Empty)) * soLuong
                    };
                    objCart.AddToCart(item);
                    Session["Cart"] = objCart;
               
            }
            JsonSerializerSettings jss = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };         
            var result = JsonConvert.SerializeObject("Thêm thành công", Formatting.Indented, jss);
            return this.Json(result, JsonRequestBehavior.AllowGet); ;
          
        }
        // cập nhật giỏ hàng theo loại sản phẩm và số lượng
      
        public ActionResult UpdateQuantity(string proID, int quantity)
        {
            int id = Convert.ToInt32(proID.Substring(7, proID.Length - 7));
            ShoppingCart objCart = (ShoppingCart)Session["Cart"];
            if (objCart != null)
            {
                objCart.UpdateQuantity(id, quantity);
                Session["Cart"] = objCart;
            }
            return RedirectToAction("index");
        }
        // giỏ hàng mặc định, nếu session = null thì hiện không có hàng trong giỏ, nếu có thì trả lại list các sản phẩm
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Title = "Giỏ hàng";
            ShoppingCartModels model = new ShoppingCartModels();
            model.Cart = (ShoppingCart)Session["Cart"];
            return View(model);
        }
        [HttpPost]
        public ActionResult ThanhToan(HoaDon hoadon,string shipName,string mobile,string address,string email)
        {
            ShopEntities shop=new ShopEntities();
            ShoppingCartModels model = new ShoppingCartModels();
            model.Cart = (ShoppingCart) Session["Cart"];
            decimal tong = model.Cart.ListItem.Sum(item => decimal.Parse(item.Price)*item.Quanlity);
            HoaDon hd=new HoaDon();
            hd.TenKH = hoadon.TenKH;
            hd.GioiTinh = hoadon.GioiTinh;
            hd.Diachi = hoadon.Diachi;
            hd.Email = hoadon.Email;
            hd.SDT = hoadon.SDT;
            hd.DiaChiGiaoHang = hoadon.DiaChiGiaoHang;
            hd.ThoiGianGiaoHang = hoadon.ThoiGianGiaoHang;
            hd.NgayTao = DateTime.Now;
            hd.TongGia = tong;
            hd.TrangThai = false;
            shop.HoaDons.Add(hd);
            shop.SaveChanges();

            KhachHang kh=new KhachHang();
            kh.TenKH = hoadon.TenKH;
            kh.GioiTinh = hoadon.GioiTinh;
            kh.DiaChi = hoadon.Diachi;
            kh.Email = hoadon.Email;
            kh.SDT = hoadon.SDT;
            shop.KhachHangs.Add(kh);
            shop.SaveChanges();
            var hoaDon = (from h in shop.HoaDons orderby h.MaHoaDon descending select h).FirstOrDefault();
            string tam = "";
            tam += "<table style='border-collapse:collapse;border:thin solid gray;width:800px'><tr><th style='border:thin solid gray'>TT</th><th  style='border:thin solid gray'>Tên sản phẩm</th><th  style='border:thin solid gray'>Số lượng</th><th style='border:thin solid gray'>Đơn giá</th><th  style='border:thin solid gray'>Thành tiền</th></tr>";
            int sott = 1;
            int tongtien = 0;
            foreach (var item in model.Cart.ListItem)
            {
                ChiTietHoaDon ct=new ChiTietHoaDon();
                ct.MaHoaDon = hoaDon.MaHoaDon;
                ct.MaSanPham = item.ProductID;
                ct.SoLuong = item.Quanlity;
                ct.TongGia = decimal.Parse(item.Total.ToString(CultureInfo.InvariantCulture)) ;
                shop.ChiTietHoaDons.Add(ct);
                shop.SaveChanges();
            }
            model.Cart.ListItem.Clear();

            double vat = tongtien * 0.1;
            double thanhtoan1 = tongtien + vat;
            tam += string.Format("<tr><td colspan=4  style='border:thin solid gray'><b>Tổng </b></td><td align='right' style='border:thin solid gray'>{0:#,##0}</td></tr>", tongtien);
            tam += string.Format("<tr><td colspan=4  style='border:thin solid gray;color:blue'><b>VAT </b></td><td align='right' style='border:thin solid gray'>{0:#,##0}</td></tr>", vat);
            tam += string.Format("<tr><td colspan=4  style='border:thin solid gray; color:red'><b>Tổng tiền: </b></td><td align='right' style='border:thin solid gray'>{0:#,##0}</td></tr>", thanhtoan1);
            //gui email:
            string senderID = "lequang.hs99@gmail.com";
            string senderPassword = "le.quang.99.gmail";

            tam += "</table>";
            string body = " " + hoadon.TenKH + " Đã được gửi mail từ website cửa kính";
            body += "Phone : " + hoadon.SDT + "<br>";
            body += "Chi tiết hóa đơn<br>";
            body += tam;
            try
            {
                MailMessage mail = new MailMessage();
                mail.To.Add(hoadon.Email);
                mail.From = new MailAddress(senderID);
                mail.Subject = "Xác nhận hóa đơn hàng công ty cửa HTĐQ";
                mail.Body = body;
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Credentials = new System.Net.NetworkCredential(senderID, senderPassword);
                smtp.Port = 587;
                smtp.EnableSsl = true;
                smtp.Send(mail);
            }
            catch (Exception)
            {

            }
            return View();
        }

        public ActionResult DienThongTin()
        {
            return View();
        }
    }
}

WebNhomKinh/Views/GioHang/DienThongTin.cshtml
@using WebNhomKinh.Models

@{
    ViewBag.Title = "DienThongTin";
    Layout = "~/Views/Shared/_Layout.cshtml";
    double total = 0;
    ShoppingCartModels model = new ShoppingCartModels();
    model.Cart = (ShoppingCart)Session["Cart"];
}

@model HoaDon
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/animate.css" rel="stylesheet" />
<link href="~/Content/owl.carousel.css" rel="stylesheet" />
<link href="~/Content/jquery.bxslider.css" rel="stylesheet" />
<link href="~/Content/responsive.css" rel="stylesheet" />
<link href="~/Content/style.css" rel="stylesheet" />
<link href="~/Content/AdminLTE.css" rel="stylesheet" />
<link href="~/Content/font-awesome.min.css" rel="stylesheet"/>
<link href="~/Content/validationEngine.jquery.css" rel="stylesheet" />
<div class="main">
    <div class="container">
        <div class="row">

            <div class="col-md-6">
                <div class="row" style="margin-top: 20px">
                    <a href="javascript:;" class="btn btn-danger btn-block btn-social  pull-left" style="width: 80%"><i class="glyphicon glyphicon-shopping-cart"></i>Giỏ hàng của bạn</a>

                </div>
                <hr/>
                @if (model != null && model.Cart != null)
                {

                    foreach (var item in model.Cart.ListItem)
                    {
                        total += item.Total;
                        <div class="cart-listing">
                            <div class="media">
                                <div class="media-left">
                                    <a href="#"><img src="@item.Image" alt="" class="img-responsive"></a>
                                </div>
                                <div class="media-body">
                                    <button type="button" class="remove-cart-item" onclick="location.href = '@Url.Action("XoaSanPham", "GioHang", new {id = item.ProductID})'">&times;</button>
                                    <h4>@item.ProductName</h4>
                                    <div class="mini-cart-qty">Số lượng: @item.Quanlity</div>
                                    <div class="mini-cart-price">Tiền:@item.Total.ToString("#,##0") VND</div>
                                </div>
                            </div>

                        </div>
                      
                    }
                }
                
                <div class="mini-cart-subtotal">Tổng: <span class="price">@total</span></div>

            </div>
            <div class="col-md-6">
                <div class="row" style="margin-top: 20px">
                    <a href="javascript:;" class="btn btn-block btn-social btn-bitbucket pull-left" style="width: 80%"><i class="fa fa-user"></i>Thông tin khách hàng</a>

                </div>
                <hr/>
                <div class="form-group">
                    @using (Html.BeginForm("ThanhToan", "GioHang", FormMethod.Post, new {enctype = "multipart/form-data",id="frmThanhToan"}))
                    {

                        <div class="form-group">
                            <label>Tên khách hàng</label>
                            @Html.TextBoxFor(m => m.TenKH, new {id = "txttenkh", @class = "form-control validate[required]", placeholder = "Tên khách hàng"})

                        </div>
                        <div class="form-group">
                            <label>Giới tính :</label>
                            @Html.RadioButtonFor(m => m.GioiTinh, new {id = "rdNam", @class = "form-control validate[required]"}) Nam
                            @Html.RadioButtonFor(m => m.GioiTinh, new {id = "rdNu", @class = "form-control validate[required]"}) Nữ
                        </div>
                        <div class="form-group">
                            <label>Địa chỉ</label>
                            @Html.TextBoxFor(m => m.Diachi, new {id = "txtdiachi", @class = "form-control validate[required]", placeholder = "Địa chỉ"})

                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            @Html.TextBoxFor(m => m.Email, new {id = "txtemail", @class = "form-control validate[required]", placeholder = "Email",type="email"})

                        </div>
                        <div class="form-group">
                            <label>Số điện thoại</label>
                            @Html.TextBoxFor(m => m.SDT, new {id = "txtsdt", @class = "form-control validate[required]", placeholder = "Số điện thoại",type="number"})

                        </div>
                        <div class="form-group">
                            <label>Địa chỉ giao hàng</label>
                            @Html.TextBoxFor(m => m.DiaChiGiaoHang, new {id = "txtdiachigiaohang", @class = "form-control validate[required]", placeholder = "Địa chỉ giao hàng"})

                        </div>
                        <div class="form-group">
                            <label>Thời gian giao hàng</label>
                            @Html.TextBoxFor(m => m.ThoiGianGiaoHang, new { id = "txtthoigiangiaohang", @class = "form-control validate[required]", placeholder = "Thời gian giao hàng" ,name = "chonngay",type="date" })

                        </div>
                        <div class="checkout-btn">
                            <input type="submit" id="btnXacNhan" class="btn btn-default btn-md fwb" value="Xác nhận thanh toán"/>

                        </div>
                    }
                </div>

            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="/Scripts/jquery.validationEngine-en.js"></script>
<script src="/Scripts/jquery.validationEngine.js"></script>

<script>
    $("#frmThanhToan").validationEngine();

    $("#btnXacNhan").click(function () {

        if ($("#frmThanhToan").valid()) {
            $("#frmThanhToan").submit();
        };
    });

  
</script>

WebNhomKinh/Views/GioHang/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(".Quanlity").change(function () {
            var quanlity = $(this).val();
            var proID = $(this).attr("id");
            $.ajax({
                url: '@Url.Action("UpdateQuantity")',
                data: { "proID": proID, "quantity": quanlity }
            });
            window.location = '/GioHang';
        });
    });
</script>

    @if (Model != null && Model.Cart != null)
    {
        <table class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <tr>
                <th>Tên sản phẩm</th>
                <th>Giá</th>
                <th>Số lượng</th>
                <th>Thành tiền</th>
            </tr>
            @{
                double total = 0;
            }
            @foreach (var item in Model.Cart.ListItem)
            {
                total += item.Total;
                <tr>
                    <td>@item.ProductName (@Html.ActionLink("Xóa", "XoaSanPham", new { id = item.ProductID }))</td>
                    <td>@item.Price VND/ 1SP</td>
                    <td>
                        @InputExtensions.TextBox(Html, "product" + item.ProductID.ToString(), item.Quanlity, new { @class = "Quanlity" ,type="number"})

                    </td>
                    <td>@item.Total.ToString("#,##0") VND</td>
                </tr>
            }
            <tr>
                <td colspan="3"><b>Tổng tiền</b></td>
                <td><b>@total.ToString("#,##0") VND</b></td>
            </tr>
        </table>
        <div class="span6" style="text-align: right">
            @using (Html.BeginForm("DienThongTin", "GioHang", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <input type="submit" class="btn btn-default btn-md fwb" value="Thanh toán" />
            }
            
        </div>
                }
                else
                {
                    <table class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
                        <tr>
                            <th>Tên sản phẩm</th>
                            <th>Giá</th>
                            <th>Số lượng</th>
                            <th>Thành tiền</th>
                        </tr>
                        <tr>
                            <td colspan="4"> Hiện chưa có sản phẩm nào trong giỏ hàng</td>
                        </tr>
                    </table>
                }
                <hr />
                

WebNhomKinh/Views/GioHang/ThanhToan.cshtml
@{
    ViewBag.Title = "ThanhToan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Đã đặt đơn hàng thành công</h3>

WebNhomKinh/Views/GioHang/ThemVaoGioHang.cshtml
@{
    ViewBag.Title = "ThemVaoGioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/nivo-slider.css" rel="stylesheet" />
<link href="~/Content/owl.carousel.css" rel="stylesheet" />
<link href="~/Content/responsive.css" rel="stylesheet" />
<link href="~/Content/style.css" rel="stylesheet" />
<link href="~/Content/animate.css" rel="stylesheet" />
<link href="~/Content/cloud-zoom.css" rel="stylesheet" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<h2>Thêm thành công</h2>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
@*<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>*@
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.nivo.slider.pack.js"></script>
<script src="~/Scripts/owl.carousel.min.js"></script>
<script src="~/Scripts/main.js"></script>
<Script>
    $(window).load(function() {
        $(".mega-menu-category").css('display', 'none');
    });
   
</Script>